server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kune?serverTimeZone=ADT
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
