package br.com.si.CrudApp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.hateoas.RepresentationModel;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "event")
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Event Model V2")
public class EventModelV2 extends RepresentationModel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter @Getter
    @ApiModelProperty(notes = "The ID, auto generated by database", required = true)
    private long id;

    @Column(name = "event_name", nullable = false, length = 50)
    @Setter @Getter
    @ApiModelProperty(notes = "The event name", required = true)
    private String eventName;

    @Column(name = "event_date", nullable = true)
    @Getter @Setter
    @ApiModelProperty(notes = "The event date", required = true)
    private Date eventDate;

    @Column(nullable = false, length = 75)
    @Setter @Getter
    @ApiModelProperty(notes = "A valid address", required = true)
    private String address;

    @Column(nullable = false, length = 100)
    @Setter @Getter
    @ApiModelProperty(notes = "Description of the event", required = true)
    private String description;


    //..many people are associated with a profession
    @ManyToOne
    @JoinColumn(name = "categories_id")
    @Getter @Setter
    private CategoryModel categories;

}
